warnings_are_errors: false

language: r

sudo: required

r_github_packages:
  - jimhester/covr

r_packages:
  - RInside

after_success:
  - Rscript -e "covr::coveralls()"

r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
