language: r

sudo: required

r_packages:
  - Rcpp
  - RInside
  - RcppArmadillo
  - devtools
  - roxygen2
  - rmarkdown
  - here

apt_packages:
  - texlive
  - ghostscript
  - texlive-fonts-extra
  - texinfo  
  
r_check_args: "--no-vignettes --no-build-vignettes --ignore-vignettes"  

addons:
  apt:
    packages:
      - valgrind

#script: 
 # - |
  #  travis_wait 160 R CMD build .
   # travis_wait 160 R CMD check RcppDeepState*tar.gz  

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
  - TEST_SUITE=CRAN
  - TEST_SUITE=TRAVIS

script:
  - R CMD INSTALL .
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi