warnings_are_errors: false

language: r

sudo: required

before_install:
  - sudo apt-get install build-essential gcc-multilib g++-multilib cmake python3-setuptools libffi-dev

r_github_packages:
  - jimhester/covr
  
before_script:
  - R -e "devtools::load_all()"

r_packages:
  - Rcpp
  - RInside
  - RcppArmadillo
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  
r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind
      
env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

