warnings_are_errors: false

language: r

sudo: required

r_github_packages:
  - jimhester/covr

r_packages:
  - RInside

after_success:
  - Rscript -e "covr::coveralls()"

r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

script: 
  - |
    travis_wait 40 R CMD build .
    travis_wait 60 R CMD check RcppDeepState*tar.gz

after_script:
  - tar -ztvf RcppDeepState_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat RcppDeepState.Rcheck/00*