warnings_are_errors: false

language: r

sudo: required

r_github_packages:
  - jimhester/covr

r_packages:
  - RInside
  - devtools
  - roxygen2

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  
r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind
      
env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'


script: 
  - |
    travis_wait 60 R CMD build .
    travis_wait 60 R CMD check RcppDeepState*tar.gz
