on:
  push:
    branches: [test-debug-symbols, logging-improvements]
  pull_request:
    branches: [test-debug-symbols, logging-improvements]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install ubuntu dependencies
        run: sudo apt-get update &&  sudo apt-get -y install build-essential gcc-multilib g++-multilib cmake python3-setuptools python3-dev libffi-dev z3 clang valgrind

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
      